[workspace]
resolver = "2"
members = ['libs/*', 'benches', 'snippetter']

[workspace.dependencies]
ansi_term = "0.12.1"
approx = "0.5"
assert-impl = "0.1.3"
indoc = "2.0.4"
itertools = "0.10"
num = "0.4.1"
ordered-float = "3.4"
rand = "0.8"
rstest = "0.18.2"
test-case = "3.0"
