[config]
default_to_workspace = false

[tasks.pre-docs]
script = '''
cargo run --bin snippetter
cp contents/* target/doc
'''

[tasks.docs]
env = { RUSTDOCFLAGS = "--html-in-header contents/header.html" }
command = "cargo"
args = ["doc", "--workspace", "--no-deps"]
dependencies = ["pre-docs"]

[tasks.pedantics]
script = '''
cargo clippy --all-targets --all-features -- -W clippy::pedantic 2>&1 | grep 'note: `-W clippy::' | sed -n 's/.*note: `-W clippy::\([a-z|-]*\).*/\1/p' | sort | uniq
'''

[tasks.clippy]
command = "cargo"
args = [
  "clippy",
  "--all-features",
  "--all-targets",
  "--",
  "-Dwarnings",
  "-Wclippy::pedantic",
  "-Aclippy::cast-possible-truncation",
  "-Aclippy::cast-possible-wrap",
  "-Aclippy::cast-precision-loss",
  "-Aclippy::cast-sign-loss",
  "-Aclippy::doc-markdown",
  "-Aclippy::manual-let-else",
  "-Aclippy::maybe-infinite-iter",
  "-Aclippy::missing-errors-doc",
  "-Aclippy::missing-panics-doc",
  "-Aclippy::module-name-repetitions",
  "-Aclippy::must-use-candidate",
  "-Aclippy::return-self-not-must-use",
  "-Aclippy::semicolon-if-nothing-returned",
  "-Aclippy::similar-names",
  "-Aclippy::uninlined-format-args",
]
