(function() {var implementors = {
"bfs01":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"bfs01/enum.Weight.html\" title=\"enum bfs01::Weight\">Weight</a>"]],
"box_segtree":[["impl&lt;'a, T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>, O:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"box_segtree/struct.SegtreeDebugList.html\" title=\"struct box_segtree::SegtreeDebugList\">SegtreeDebugList</a>&lt;'a, T, O&gt;"]],
"cht":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"cht/enum.Convex.html\" title=\"enum cht::Convex\">Convex</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"cht/enum.Concave.html\" title=\"enum cht::Concave\">Concave</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"cht/struct.Quadratic.html\" title=\"struct cht::Quadratic\">Quadratic</a>"]],
"dinic":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"dinic/struct.Edge.html\" title=\"struct dinic::Edge\">Edge</a>&lt;T&gt;"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"dinic/struct.EdgeKey.html\" title=\"struct dinic::EdgeKey\">EdgeKey</a>"]],
"fp":[["impl&lt;M:&nbsp;<a class=\"trait\" href=\"fp/trait.Mod.html\" title=\"trait fp::Mod\">Mod</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"fp/struct.Fp.html\" title=\"struct fp::Fp\">Fp</a>&lt;M&gt;"]],
"grid":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"grid/enum.Dihedral.html\" title=\"enum grid::Dihedral\">Dihedral</a>"]],
"heap_tricks":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"heap_tricks/struct.Nop.html\" title=\"struct heap_tricks::Nop\">Nop</a>"],["impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"heap_tricks/struct.Sum.html\" title=\"struct heap_tricks::Sum\">Sum</a>&lt;T&gt;"]],
"hld":[["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"hld/struct.IterV.html\" title=\"struct hld::IterV\">IterV</a>&lt;'a&gt;"],["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"hld/struct.IterE.html\" title=\"struct hld::IterE\">IterE</a>&lt;'a&gt;"]],
"lin_ineq":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"lin_ineq/struct.Interval.html\" title=\"struct lin_ineq::Interval\">Interval</a>&lt;T&gt;"]],
"mincost_flow":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"mincost_flow/struct.Edge.html\" title=\"struct mincost_flow::Edge\">Edge</a>"]],
"not_nan":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> + <a class=\"trait\" href=\"not_nan/trait.Float.html\" title=\"trait not_nan::Float\">Float</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"not_nan/struct.NotNaN.html\" title=\"struct not_nan::NotNaN\">NotNaN</a>&lt;T&gt;"]],
"rational":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> + <a class=\"trait\" href=\"rational/trait.Signed.html\" title=\"trait rational::Signed\">Signed</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rational/struct.Rational.html\" title=\"struct rational::Rational\">Rational</a>&lt;T&gt;"]],
"reverse":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"reverse/struct.Reverse.html\" title=\"struct reverse::Reverse\">Reverse</a>&lt;T&gt;"]],
"vec_lines":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.68.2/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"vec_lines/struct.Line.html\" title=\"struct vec_lines::Line\">Line</a>&lt;T&gt;"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()