[package]
name = "benches"
version = "0.1.0"
edition = "2021"

[dependencies]
fp = { path = "../libs/fp" }
fp_fft = { path = "../libs/fp_fft" }
fp_fps = { path = "../libs/fp_fps" }
bipartite_matching = { path = "../libs/bipartite_matching" }
max_flow = { path = "../libs/max_flow" }
rand = "0.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "fft_benchmark"
harness = false

[[bench]]
name = "fps_inv_benchmark"
harness = false

[[bench]]
name = "bipartite_matching_benchmark"
harness = false

[[bench]]
name = "max_flow_benchmark"
harness = false
